version: 1.0.{build}

branches:
  only:
    - master
    - appveyor_nonsense

services:
  - postgresql95

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain stable --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

before_test:
  - SET PATH=%PATH%;C:\MinGW\bin
  - SET PATH=C:\Program Files\PostgreSQL\9.5\bin;%PATH%
  # `cargo test` is broken with rustup. https://github.com/rust-lang/cargo/issues/3394
  - ps: $Env:PATH += ";" + (get-item (rustup which cargo)).Directory.FullName
  - createdb diesel_test

test_script:
  - cd diesel
  - cargo test --features "%backend% extras"
  - cd ../diesel_cli
  - cargo test --no-default-features --features "%backend%"
  - cd ../diesel_codegen
  - cargo test --features "%backend%"
  - cd ../diesel_tests
  - cargo test --features "%backend%"

environment:
  global:
    PGUSER: postgres
    PGPASSWORD: Password12!

  matrix:
  #    - channel: stable
  #      target: x86_64-pc-windows-msvc
    - target: x86_64-pc-windows-gnu
      backend: postgres
      DATABASE_URL: postgres://postgres:Password12!@localhost/diesel_test
    - target: x86_64-pc-windows-gnu
      backend: sqlite
      DATABASE_URL: test.db
