version: 1.0.{build}

branches:
  only:
    - master
    - appveyor_nonsense

services:
  - postgresql95

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

before_test:
  - SET PATH=%PATH%;C:\MinGW\bin
  - '"C:\Program Files\PostgreSQL\9.5\pg_env.bat"'
  - echo %PATH%
  - pg_config --libdir
  - pg_config
  - createdb diesel_test

test_script:
  # - cd diesel
  # - cargo test --features "postgres extras"
  # - cd ../diesel_cli
  # - cargo test --no-default-features --features "postgres"
  - cd ../diesel_codegen
  - cargo test --features "postgres" --verbose -- --nocapture
  - cd ../diesel_tests
  - cargo test --features "postgres"

environment:
  global:
    DATABASE_URL: postgres://postgres:Password12!@localhost/diesel_test
    PGUSER: postgres
    PGPASSWORD: Password12!

  matrix:
  # Stable 64-bit MSVC
  #    - channel: stable
  #      target: x86_64-pc-windows-msvc
  #  # Beta 64-bit MSVC
  #    - channel: beta
  #      target: x86_64-pc-windows-msvc
  #  # Nightly 64-bit MSVC
  #    - channel: nightly
  #      target: x86_64-pc-windows-msvc

### GNU Toolchains ###

  # # Stable 64-bit GNU
  #   - channel: stable
  #     target: x86_64-pc-windows-gnu
  # # Beta 64-bit GNU
  #   - channel: beta
  #     target: x86_64-pc-windows-gnu
  # Nightly 64-bit GNU
    - channel: nightly
      target: x86_64-pc-windows-gnu
